### PR TITLE
Use Hypothesis to generate introspection data

### PR DESCRIPTION
**Pull request by mulkieran**
Ultimately, this is a much better approach than simply grabbing illustrative
examples.

Also, improve the tests for managed_object result. This allows to remove
one nocover pragma for a RuntimeError, which is a good sign.

Signed-off-by: mulhern <amulhern@redhat.com>

### CODE REVIEW

**Comment by mulkieran** [comment]
I think strategy might as well be extended a bit further...

**Comment by mulkieran** [comment]
Ok. Strategy is now complete.

**Comment by mulkieran** [comment]
Still ready to go, but used recursive strategy for node_strategy. At this point, all the ```*_strategy()``` functions could be constants, but we expect that in future they will take interesting parameters, so leaving them as functions.

**Comment by agrover** [comment]
so this no longer uses examples from our actual XML introspection, but.. generates arbitrary valid dbus xml for testing purposes?

**Comment by mulkieran** [comment]
> so this no longer uses examples from our actual XML introspection, but.. generates arbitrary valid dbus xml for testing purposes? Just making sure I'm understanding.

Precisely. The reason I didn't do this originally was that I had no idea what the valid format of such data would be, because I really only had examples from stratisd. But since then, I discovered that the published dtd, which looks like a blank page in my browser, actually does contain the official dtd. So that meant that I felt I had enough knowledge about what the format of the introspection data should be that I could make a reasonable Hypothesis strategy to generate arbitrary examples of that data.

**Comment by agrover** [comment]
Cool! :+1:

**Pull request merged**
