### PR TITLE
Export improved interface for managed objects queries

### PR DESCRIPTION
**Pull request by mulkieran**
Resolves: #13

### CODE REVIEW

**Comment by mulkieran** [comment]
Failure of coverage task due to Hypothesis health check failure, most likely due to the fact that interfaces can be of arbitrary size, and probably one got super larger. #15 will probably fix this problem for a while, but likely restrictions should be put on signature size as well.

**Comment by mulkieran** [comment]
See https://github.com/stratis-storage/stratis-cli/pull/148 for necessary changes to stratis-cli.

**Comment by agrover** [comment]
lgtm

**Comment by mulkieran** [comment]
I added negation, so there would be a functionally complete set of boolean operators. Otherwise, the same as before.

**Comment by mulkieran** [comment]
AFAIC, this is ready to go.

**Pull request merged**
